spring.application.name=mddapi

spring.datasource.url=jdbc:mysql://localhost:3306/mdd?createDatabaseIfNotExist=true
spring.datasource.username=mdd
spring.datasource.password=mdd123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true